### ISSUE TITLE
Is this project interested in add `lua_ls`'s annotations for completion

### ISSUE THREAD

**Issue by AbaoFromCUG** [willothy/wezterm.nvim#18]
Refer to https://github.com/wez/wezterm/issues/3132 , wezterm export `annotations` for itself, we need to add `annotations` manually. 
Lua_ls support add addition definition files for library. There are some pretty good annotations, e.g. https://github.com/jason0x43/dotfiles/tree/master/config/nvim/lua/user/types/wezterm

I would like to add these annotations in this awesome plugin.  The annotations will be added to `wezterm.nvim/types/`,  which follow the rules of `https://github.com/folke/neodev.nvim`.

Thanks.

**Comment by willothy** [comment]
Absolutely, I should've done this already. I'll add type annotations ASAP. I'll likely just inline them though instead of using a type defs file.

**Comment by willothy** [comment]
Actually I just realized that I already have type annotations in the code :)

Are the types not working for you? It might be that your runtime paths for lua ls don't include your plugin dirs.

**Comment by AbaoFromCUG** [comment]
No, I mean, the type annotations of wezterm config, not this neovim-plugin. As you know,  wezterm config is written by lua too.

But thanks for your reply. I already had added some types file manually for myself

**Comment by willothy** [comment]
Ohhh, my bad. No, sorry, I think that falls outside the scope of this plug-in since this is just an API for Neovim to control Wezterm. It would introduce a lot of maintenance burden for me to maintain types for the entire Wezterm API. 

For my Wezterm config I just have some types I've defined myself as well, so I'd recommend sticking with that. If you wanted to maintain types for Wezterm's config that would be awesome though!
